.TH HISTED 1
.SH NAME
histed \- modify files from their last edited times.
.SH SYNOPSIS
.B histed
[\fB\-dmy\fR]
.IR time
[\fB\ (mv)(rm)(cp)\fR]
.SH DESCRIPTION
This program can move,remove or copy your old files.
.SH OPTIONS
.TP 
.BR Time_options
.BR \-d  
\- Day based old setting.\n

.BR \-m  
\- Month based old setting.\n

.BR \-y  
\- Year based old setting.\n
.TP 
.BR Command_options 
.BR mv 
\- move old files
 
.BR rm 
\- remove old files
 
.BR cp  
\- copy old files
.SH BUGS
program excepts a month as 30 days and a year as 365 day.

