.TH MAKEGEN 1
.SH NAME
makegen \- generating a makefile for a C project.
.SH SYNOPSIS
.B makegen
.IR executablefile
.SH DESCRIPTION
.B makegen
is a function that generating makefile with linking C files with headers.
.SH OPTIONS
There is no option assigned yet.
.SH BUGS
For better output you should set your files correctly.
All headers and C files should be in one file.

